<header class="main-header">
	<h1>Envoyer des données</h1>
	<p>Un formulaire de connexion</p>
</header>                    
                
            
<?php if(!empty($connect) ) : ?>

<p>Connexion réussie</p>

<?php else : ?>

	<?php if( isset($connect) ) : ?>
	<p>Erreur de connexion</p>
	<?php endif; ?>
	
<form method="post">
	<fieldset>
		<legend>Se connecter</legend>
		<p class="field">
			<label for="username">Identifiant</label>
			<input type="text" name="username" id="username">
		</p>
		<p class="field">
			<label for="password">Mot de passe</label>
			<input type="password" name="password" id="password">
		</p>
	</fieldset>
	<input type="submit" value="Se connecter">
</form>
<?php endif; ?>