<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="utf-8">
  <title>Painter SVG</title>
  <meta name="description" content="Module JS1 - Exercice Icons">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link
    href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,600,700,800&display=swap"
    rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Lobster&display=swap"
        rel="stylesheet">
  <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css">
  <link href="./css/lib/normalize.css" rel="stylesheet">
  <link href="./css/lib/layout.css" rel="stylesheet">
  <link href="./css/lib/theme.css" rel="stylesheet">
</head>
<body>
<header class="banner">
  <a class="banner-link" href="./">
    <strong class="banner-title">Painter SVG</strong>
    <small>Avec PHP et en POO !</small>
  </a>
</header>

<main class="project container">
  <svg width="100" height="100">
    <circle cx="50" cy="50" r="40" stroke="green" stroke-width="4" fill="yellow"/>
  </svg>
  <svg width="400" height="110">
    <rect width="300" height="100" x="50" y="5" style="fill: #a4bfa4; stroke-width: 3;
    stroke: rgba(0,0,0,.8);"/>
  </svg>
  <svg width="400" height="180">
    <rect x="50" y="20" width="150" height="150" style="fill: #da7635; stroke: #de5833;
    stroke-width: 5;fill-opacity: 0.1;stroke-opacity: 0.9"/>
  </svg>
  <svg width="400" height="180">
    <rect x="50" y="20" rx="20" ry="40" width="150" height="150" style="fill: #555555;
    stroke:
    #111111;stroke-width: 5; opacity: 0.5"/>
  </svg>
  <svg width="500" height="140">
    <ellipse cx="200" cy="80" rx="100" ry="50"/>
  </svg>
</main>

<footer id="mentions" class="mentions">
  <p><strong> &copy; Olivier Meunier - Tous&nbsp;droits&nbsp;réservés</strong>
</footer>

<!-- Affichage du support -->
<script src=".resources/js/resources.js" data-md=".resources/statement.md"></script>

</body>
</html>
