<section>
    <h2>Nos dernières publications</h2>
    <?php foreach ($articles as $article): ?>
        <article>
            <p><?=$article['category_label'];?></p>
            <img src="<?=assetUpload($article['image']);?>" alt="">
            <h3><?=$article['title'];?></h3>
            <small><?=(new DateTimeImmutable($article['createdAt']))->format('d/m/Y');?></small>
            <p><?=mb_substr($article['content'], 0, 150);?>...</p>
            <a href="index.php?action=article&idArticle=<?=$article['idArticle'];?>">Lire la suite</a>
        </article>
    <?php endforeach; ?> 
</section>
   