<!-- Message d'erreur --> 
<?php if (isset($error)): ?>
    <p class="error"><?=$error;?></p>
<?php endif; ?>

<!-- Formulaire de connexion -->
<form action="index.php?action=login" method="POST">
    <fieldset>
        <legend>Connexion</legend>
        <div class="field-list">
            <label for="email">Email</label>
            <input type="text" id="email" name="email">
        </div> 
        <div class="field-list">
            <label for="password">Mot de passe</label>
            <input type="password" id="password" name="password">
        </div> 
        <input class="btn" type="submit" value="Connexion">
    </fielset>
</form>