<!-- Formulaire de création de compte -->
<form action="index.php?action=signup" method="POST">
    <fieldset>
        <legend>Créez votre compte client</legend>
        <div class="field-list">
            <label for="lastname">Nom</label>
            <input type="text" id="lastname" name="lastname" value="<?=$lastname?>">
            <?php if (isset($errors['lastname'])): ?>
                <p class="error"><?=$errors['lastname'];?></p>
            <?php endif; ?>
        </div> 
        <div class="field-list">
            <label for="firstname">Prénom</label>
            <input type="text" id="firstname" name="firstname" value="<?=$firstname?>">
            <?php if (isset($errors['firstname'])): ?>
                <p class="error"><?=$errors['firstname'];?></p>
            <?php endif; ?>
        </div> 
        <div class="field-list">
            <label for="email">Email</label>
            <input type="text" id="email" name="email" value="<?=$email?>">
            <?php if (isset($errors['email'])): ?>
                <p class="error"><?=$errors['email'];?></p>
            <?php endif; ?>
        </div> 
        <div class="field-list">
            <label for="password">Mot de passe</label>
            <input type="password" id="password" name="password">
            <?php if (isset($errors['password'])): ?>
                <p class="error"><?=$errors['password'];?></p>
            <?php endif; ?>
        </div> 
        <div class="field-list">
            <label for="password-confirm">Mot de passe (confirmation)</label>
            <input type="password" id="password-confirm" name="password-confirm">
            <?php if (isset($errors['password-confirm'])): ?>
                <p class="error"><?=$errors['password-confirm'];?></p>
            <?php endif; ?>
        </div> 
        <input class="btn" type="submit" value="Créer mon compte">
    </fielset>
</form>