<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>ToDoList</title>
    <link rel="stylesheet" href="./css/style.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Rock+Salt&display=swap" rel="stylesheet">
</head>
<body>
<div class="PageWrapper">
    <header class="TopBanner">
        <h1 class="TopBanner-title">Ma ToDo List !</h1>
        <div class="glowy-wrap"><img class="glowy" src="./img/liz_runestone_blue.png" alt=""></div>
    </header>
    <main class="MainContent">
        <form action="<?php echo htmlspecialchars($_SERVER['PHP_SELF']) ?>" method="post" class="MainContent-form Form">
            <fieldset>
                <legend class="Form-title"> Liste des tâches :&nbsp;</legend>
                <?php if ($tasks) : ?>
                    <input type="submit" class="Form-submit" value="Supprimer" name="supprimer">
                    <ul class="Form-menu">
                        <?php foreach ($tasks as $index => $task) : ?>
                            <li class="Form-menu-task">
                                <input type="checkbox" name="indexes[]" id="task#<?= $index ?>" value="<?= $index ?>">
                                <label class="strikethrough" for="task#<?= $index ?>">
                                    <?= $task['titre'] ?>
                                </label>&nbsp;
                                <button title="supprimer cette tâche"><i class="fas fa-trash-alt"></i></button>
                                <button title="modifier cette tâche"><i class="fas fa-edit"></i></button>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                <?php else : ?>
                    <h2>Ah comme ça on risque pas de mal faire, c'est sûr ! ...</h2>
                <?php endif; ?>
            </fieldset>
        </form>
        <form action="<?php echo htmlspecialchars($_SERVER['PHP_SELF']) ?>" method="post" class="MainContent-form Form">
            <fieldset>
                <legend class="Form-title"> Ajouter une tâche :&nbsp;</legend>
                <!--                --><?php //if (isset())?>
                <!--                --><?php //?>
                <ul class="Form-menu">
                    <li class="Form-menu-item">
                        <label for="titre">Titre : </label>
                        <input type="text" id="titre" name="titre"
                               value="<?php if (isset($arr['titre'])) echo htmlspecialchars($arr['titre']); ?>">
                    </li>
                    <li class="Form-menu-item">
                        <label for="description">Description : </label>
                        <textarea id="description" name="description" rows="5">
                            <?php if (isset($arr['description'])) echo htmlspecialchars($arr['description']) ?>
                        </textarea>
                    </li>
                    <li class="Form-menu-item">
                        <label for="date">Date limite : </label>
                        <input type="date" id="date" name="date"
                               value="<?php if (isset($arr['date'])) echo htmlspecialchars($arr['date']) ?>">
                    </li>
                    <li class="Form-menu-item">
                        <p>Priorité : </p>
                        <label for="basse"> basse </label>
                        <input type="radio" name="priorite" id="basse" value="basse"
                            <?php if ($arr['priorite'] === 'basse') echo "checked" ?>>
                        <label for="moyenne"> moyenne </label>
                        <input type="radio" name="priorite" id="moyenne" value="moyenne"
                            <?php if ($arr['priorite'] === 'moyenne') echo "checked" ?>>
                        <label for="haute"> haute </label>
                        <input type="radio" name="priorite" id="haute" value="haute"
                            <?php if ($arr['priorite'] === 'haute') echo "checked" ?>>
                    </li>
                </ul>
                <input type="submit" class="Form-submit" value="Enregistrer" title="ZBRA" name="enregistrer">
            </fieldset>
        </form>
    </main>
</div>
<div style="display: none">
    <svg width="1370" height="1518">
        <defs>
            <clipPath id="svgPath">
                <path fill="#FFFFFF" stroke="#000000" stroke-width="1.5794" stroke-miterlimit="10"
                      d="M323.5 241L1 812L28.5 1065.5C31.6667 1151.5 47.2 1338.3 84 1397.5C130 1471.5 148.5 1466.5 185.5 1443.5C215.1 1425.1 603.167 1484.83 793.5 1517C838 1472.5 931.7 1379.8 950.5 1365C969.3 1350.2 1194.67 1005.5 1305 835C1312.67 727.5 1335.4 509.8 1365 499C1394.6 488.2 1254.33 162.5 1180.5 1C941 18 451.8 55.7 411 70.5C370.2 85.3 335.667 190.333 323.5 241Z"/>
            </clipPath>
        </defs>
    </svg>
</div>
<script src="./js/main.js"></script>
<script src="https://kit.fontawesome.com/c6a24866e1.js" crossorigin="anonymous"></script>
</body>
</html>