<h2 class="mt-5">Dashboard : liste des articles</h2>

<nav>
    <a class="btn btn-primary my-3" href="index.php?action=admin_article_add" title="Rédiger un article">
        <i class="fa-solid fa-circle-plus"></i> Rédiger un article</a>
</nav>

<table class="table table-dark table-striped">
    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Titre</th>
            <th scope="col">Catégorie</th>
            <th scope="col">Date de création</th>
            <th scope="col">Photo</th>
            <th scope="col">Actions</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($articles as $article): ?>
            <tr>
                <th scope="row"><?=intval($article->getId());?></th>
                <td><?=htmlspecialchars($article->getTitle());?></td>
                <td><?=htmlspecialchars($article->getCategory()->getLabel());?></td>
                <td><?=($article->getCreatedAt())->format('d/m/Y');?></td>
                <td>
                    <img class="thumbnail" src="<?=assetUpload($article->getImage());?>" alt="">
                </td>
                <td>
                    <a href="index.php?action=admin_article_edit&idArticle=<?=intval($article->getId());?>" class="btn btn-primary" title="Modifier l'article">
                        <i class="fa-solid fa-pen-to-square"></i>
                    </a>  
                    <a href="index.php?action=admin_article_delete&idArticle=<?=intval($article->getId());?>" class="btn btn-danger" title="Supprimer l'article">
                        <i class="fa-solid fa-trash-can"></i>
                    </a>
                </td>
            </tr>
        <?php endforeach; ?> 
    </tbody>
</table>