<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mon blog !</title>
</head>
<body>
    <header>
        <h1>Bienvenue sur blog !</h1>
        <nav>
            <a href="index.php">Accueil</a>
            <a href="index.php?action=contact">Contact</a>
        </nav>
    </header>
    <main>
        <?php include TEMPLATE_DIR . '/' . $template . '.phtml'; ?>
    </main>
    <footer>
        <nav>
            <a href="index.php?action=mentions">Mentions légales</a>
        </nav>
    </footer>
</body>
</html>