<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <title>Painter SVG</title>
    <meta name="description" content="Module JS1 - Exercice Icons">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,600,700,800&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lobster&display=swap" rel="stylesheet"> 
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css"> -->
    <link href="./css/lib/normalize.css" rel="stylesheet">
    <link href="./css/lib/layout.css" rel="stylesheet">
    <link href="./css/lib/theme.css" rel="stylesheet">
  </head>
  <body>
    <header class="banner">
      <a class="banner-link" href="./">
        <strong class="banner-title">Painter SVG</strong>
        <small>Avec PHP et en POO !</small>
      </a>
    </header>

    <main class="project container">

      <!-- Afficher ici les formes géométriques -->
      <?=$svg;?>
     
    </main>

    <footer id="mentions" class="mentions">
      <p><strong> &copy; Olivier Meunier - Tous&nbsp;droits&nbsp;réservés</strong>
    </footer>

    <!-- Affichage du support -->
    <!-- <script src=".resources/js/resources.js" data-md=".resources/statement.md"></script> -->

  </body>
</html>
