<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Interface d'administration</title>

    <!-- Font Awesome --> 
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">

    <!-- CSS Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- CSS custom -->
    <link href="css/admin.css" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
            <div class="container">
                <a class="navbar-brand" href="index.php?action=admin">Administration</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav me-auto my-2 my-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" href="index.php" target="_blank">Site public</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav">
                        <?php if (isConnected()): ?>
                            <li class="nav-item">
                                <a class="nav-link" href="index.php?action=logout">
                                    <i class="fa-solid fa-arrow-right-from-bracket"></i> Déconnexion</a>
                            </li>
                        <?php else: ?>
                            <li class="nav-item">
                                <a class="nav-link" href="index.php?action=login">
                                    <i class="fa-solid fa-arrow-right-to-bracket"></i> Connexion</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="index.php?action=signup">
                                    <i class="fa-solid fa-user-plus"></i> Créer un compte</a>
                            </li>
                        <?php endif; ?>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container mt-3">
        <div class="row">
            <div class="col-md-12">
                <main>
                    <!-- Affichage des messages flash -->
                    <?php if (isset($flashMessage)): ?>
                        <p><?=htmlspecialchars($flashMessage);?></p>
                    <?php endif; ?>

                    <!-- Inclusion du template de la page --> 
                    <?php include TEMPLATE_DIR . '/admin/' . $template . '.phtml'; ?>
                </main>
            </div>
        </div>
        <footer>
            <nav>
                <a href="index.php?action=mentions">Mentions légales</a>
            </nav>
        </footer>
    </div>   
</body>
</html>