<section class="zoom">
  <h2>Galerie 2</h2>
  <!-- -- Une liste des photos miniatures -->
  <ul class="zoom-list">
    <li class="zoom-list-item">
      <img
        data-gallery=#gallery2
        class="zoom-thumbnail is-active"
        src="./medias/galery2/1.jpg"
        alt="Photo 1">
    </li>
    <li class="zoom-list-item">
      <img
        data-gallery=#gallery2
        class="zoom-thumbnail"
        src="./medias/galery2/2.jpg"
        alt="Photo 2"
        title="Zoom sur l'image">
    </li>
    <li class="zoom-list-item">
      <img
        data-gallery=#gallery2
        class="zoom-thumbnail"
        src="./medias/galery2/3.jpg"
        alt="Photo 3"
        title="Zoom sur l'image">
    </li>
  </ul>
  <!-- --Une seule figure pour présenter la version agrandie (la première étant chargée au démarrage ) -->
  <figure id="gallery2" class="zoom-figure animate__animated animate__zoomIn">
    <figcaption class="zoom-caption">
      Photo 1
    </figcaption>
    <img
      class="zoom-picture"
      src="./medias/galery2/1.jpg" alt="">
  </figure>
</section>