<section class="zoom">
  <h2>Galerie 1</h2>
  <!-- -- Une liste des photos miniatures -->
  <ul class="zoom-list">
    <li class="zoom-list-item">
      <img
        class="zoom-thumbnail is-active"
        src="./medias/galery1/1.jpg"
        alt="Photo 1">
    </li>
    <li class="zoom-list-item">
      <img
        class="zoom-thumbnail"
        src="./medias/galery1/2.jpg"
        alt="Photo 2"
        title="Zoom sur l'image">
    </li>
    <li class="zoom-list-item">
      <img
        class="zoom-thumbnail"
        src="./medias/galery1/3.jpg"
        alt="Photo 3"
        title="Zoom sur l'image">
    </li>
    <li class="zoom-list-item">
      <img
        class="zoom-thumbnail"
        src="./medias/galery1/4.jpg"
        alt="Photo 4"
        title="Zoom sur l'image">
    </li>
    <li class="zoom-list-item">
      <img
        class="zoom-thumbnail"
        src="./medias/galery1/5.jpg"
        alt="Photo 5"
        title="Zoom sur l'image">
    </li>
  </ul>
  <!-- --Une seule figure pour présenter la version agrandie (la première étant chargée au démarrage ) -->
  <figure class="zoom-figure animate__animated animate__zoomIn">
    <figcaption class="zoom-caption">
      Photo 1
    </figcaption>
    <img
      class="zoom-picture"
      src="./medias/galery1/1.jpg" alt="">
  </figure>
</section>