<header class="main-header">
  <h1>Recevoir et afficher des données</h1>
  <p>2 moteurs : texte simple et récupération d'un JSON</p>
</header>
<nav>
  <h2>Boutons de chargement</h2>
  <button id="btn-ajax1" data-url="page1.phtml" type="button">Récupérer du texte formaté en HTML</button>
  <button id="btn-ajax2" data-url="page2.php" type="button">Récupérer un contenu JSON</button>
</nav>
<div id="ajax">
  <article>
    <h2>Affichage au chargement</h2>
    <p>Cet article sera remplacé en AJAX</p>
  </article>
</div>