  <header class="main-header">
    <h1><img src="img/ajax.png" alt="AJAX"></h1>
    <p>Asynchronous JavaScript And XML</p>
  </header>
  <article>
    <h2>Le concept d'AJAX</h2>
    <p>AJAX (Asynchronous JavaScript and XML) est le résultat d'un ensemble de technologies permettant de rafraîchir une partie de page web sans recharger la page complète.</p>
    <p>Ajax va pouvoir récupérer ou transmettre des données sur un serveur, à partir d'un événement javaScript (moteur AJAX) programmé sur la page.</p>
  </article>
  <article>
    <h2>Format des données échangées</h2>
    <p>L’objet <strong>XMLHttpRequest</strong> permet d’échanger des informations sous différents formats :</p>
    <ol>
      <li><strong>Texte simple</strong> <small>(impossible à mettre en forme)</small></li>
      <li><strong class="tag">HTML</strong> <small>(peut se révéler assez lourd quand il s'agit d'un grand volume de données)</small></li>
      <li><strong>XML</strong> idem HTML <small>(permet de manipuler les données avec les fonctions DOM)</small></li>
      <li><strong class="tag">JSON</strong> leger, il permet de structurer l'information en utilisant la syntaxe objet de JavaScript</li>
    </ol>
  </article>
  <article>
    <h2>L'objet XMLHttpRequest</h2>
    <p>XMLHttpRequest est un objet ActiveX ou JavaScript qui permet d'obtenir des données au format XML, JSON, mais aussi HTML, ou encore texte simple à l'aide de requêtes HTTP.</p>
    <p>L'utilisation de l'objet XHR se fait en deux étapes distinctes :</p>
    <ol>
      <li>Préparation et envoi de la requête</li>
      <li>Réception des données</li>
    </ol>
  </article>
