<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Formulaire de contact</title>
</head>
<body>
<h1>Formulaire de contact pour s'abonner à la newsletter !</h1>
<form action="persitent-contacts.php" method="post">
    <fieldset>
        <legend>Mes coordonnées :</legend>
        <label for="email">Mon email : </label>
        <input type="text" name="email" id="email" value="">
        <button type="submit">Je m'abonne !</button>
    </fieldset>
</form>
<hr>
<?php if ($error) :?>
<h3>ERREUR DE TRAITEMENT : <?=$error?></h3>
<?php endif;?>
<h2>Liste des emails des abonnés :</h2>
<?php if ($newsletterSubs) : ?>
    <ul>
        <?php foreach ($newsletterSubs as $email) : ?>
            <li><?= $email ?> </li>
        <?php endforeach ?>
    </ul>
<?php endif; ?>
</body>
</html>
