<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <title>PHP</title>
    <link rel="stylesheet" href="order.css">
</head>
<body>
<section>
    <h1>Bons de commande</h1>

    <a href="index.php">Retourner à l'accueil</a>

    <article class="order-form-customer">
        <h2><?=$customer['customerName']?></h2>
        <h3><?=$customer['contactFirstname']?> <?=$customer['contactLastname']?></h3>
        <p><?=$customer['addressLine1']?></p>
        <p><?=$customer['addressLine2']?></p>
        <p><?=$customer['city']?></p>
    </article>

    <table class="standard-table">
        <caption>Bon de commande n° <?= $orderNumber ?></caption>
        <thead>
        <tr>
            <th>Produit</th>
            <th class="money-column">Prix Unitaire</th>
            <th>Quantité</th>
            <th class="money-column">Sous-total</th>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <th colspan="3">Total HT</th>
            <th><?=number_format($total, 2);?> €</th>
        <tr>
        <tr>
            <th colspan="3">Montant TVA</th>
            <th><?=number_format($total * 0.2, 2);?> €</th>
        <tr>
        <tr>
            <th colspan="3">Total TTC</th>
            <th><?=number_format($total * 1.2, 2);?> €</th>
        <tr>
        </tfoot>
        <tbody>
        <?php foreach ($orderLines as $orderLine): ?>
            <tr>
                <td><?=$orderLine['productName'];?></td>
                <td><?=number_format($orderLine['priceEach'], 2);?> €</td>
                <td><?=$orderLine['quantityOrdered'];?></td>
                <td><?=number_format($orderLine['total'], 2);?> €</td>
            </tr>
        <?php endforeach ;?>
        </tbody>
    </table>
</section>
</body>
</html><?php
