<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="./css/style.css">
    <title>Test</title>
</head>
<body>
<div class="PageWrapper">
    <header class="TopBanner">
        <H1 class="TopBanner-title">Je crée mon compte client</H1>
    </header>
    <main class="MainContent">
        <form action="<?php echo htmlspecialchars($_SERVER['PHP_SELF']) ?>" method="post">
            <fieldset class="Form">
                <legend class="Form-title">&nbspMes informations&nbsp</legend>
                <label for="nom">Nom : &nbsp</label>
                <?php if (isset($errors['nom'])) echo htmlspecialchars($errors['nom']) ?>
                <input type="text" class="Form-field" name="nom" id="nom" value="<?php if (isset($nom)) echo $nom ?>">
                <label for="prenom">Prénom : &nbsp</label>
                <?php if (isset($errors['prenom'])) echo htmlspecialchars($errors['prenom'])?>
                <input type="text" class="Form-field" name="prenom" id="prenom" value="<?php if (isset($prenom)) echo $prenom ?>">
                <label for="email">Email : &nbsp</label>
                <?php if (isset($errors['email'])) echo htmlspecialchars($errors['email'])?>
                <input type="text" class="Form-field" name="email" id="email" value="<?php if (isset($email)) echo $email ?>">
                <label for="password">Mot de passe : &nbsp</label>
                <?php if (isset($errors['password'])) echo htmlspecialchars($errors['password'])?>
                <input type="password" class="Form-field" name="password" id="password">
                <label for="confirmation">Confirmation du mot de passe (doit être identique) : &nbsp</label>
                <?php if (isset($errors['confirmation'])) echo htmlspecialchars($errors['confirmation'])?>
                <input type="password" class="Form-field" name="confirmation" id="confirmation">
                <input type="submit" class="Form-submit" value="Valider">
            </fieldset>
        </form>
    </main>
</div>
</body>
</html>