<!DOCTYPE html>
<html class="no-js" lang="fr">
  <head>
      <meta charset="utf-8">
      <title>Zoom sur image</title>
  		<meta name="description" content="Mise en place HTML/CSS">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link href="./css/main.min.css" rel="stylesheet">
      <script src="js/zoom.js"></script>
  </head>
  <body>
    <header class="banner">
      <a class="site-logo" href="../">Zoom</a>
      <p class="site-description">Étape 1 : mise en place</p>
      <nav>
        <a href="./">Accueil</a>
        <a href="?action=pixabay">Interface Pixabay</a>
      </nav>
    </header>
    <main>
      <?php include TEMPLATE_DIR . '/' . $template . '.phtml'; ?>
    </main>

    <footer class="footer">
      <p>Formation Développeur Web - Module javaScript - &copy; Véronique CUOMO<p>
      <p>Nous remercions les auteurs des photos présentées sur ce site, récoltées sur <a href="https://pixabay.com/fr/">Pixabay</a></p>
      <a id="goTop" href="#" title="Remonter">&UpArrow;</a>
    </footer>

  <?php if ($template === 'pixabay') : ?>
    <script src="../public/js/ajax.js"></script>
    <script src="../public/js/pixabay.js"></script>
  <?php endif; ?>
  </body>
</html>
